name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # lub 'master', jeśli taka jest Twoja gałąź główna

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase Hosting and Functions
      run: firebase deploy --only hosting,functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
